# Generated by Django 2.2.1 on 2019-06-17 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20190613_1813'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
